version: 2
jobs:
  build:
    environment:
      #IMAGE_NAME: jonathancardoso/building-on-ci
    docker:
      - image: circleci/openjdk:latest
    steps:
      - checkout 
      #- setup_remote_docker
      - run:
          name: Build Docker image
          command: echo "working_directory:${CIRCLE_WORKING_DIRECTORY}";
                   mkdir -p "${CIRCLE_WORKING_DIRECTORY}/../i2b2-quickstart/local/unzipped_packages/${CIRCLE_PROJECT_REPONAME}";
                   cp -rv  "${CIRCLE_WORKING_DIRECTORY}" "${CIRCLE_WORKING_DIRECTORY}/../i2b2-quickstart/local/unzipped_packages/";
                   mv "${CIRCLE_WORKING_DIRECTORY}/../i2b2-quickstart/local/unzipped_packages/${CIRCLE_PROJECT_REPONAME}" "${CIRCLE_WORKING_DIRECTORY}/../i2b2-quickstart/local/unzipped_packages/${CIRCLE_PROJECT_REPONAME}";
                   cd ..;
                   ls -l;
                   git clone --depth 1 https://github.com/waghsk/i2b2-quickstart;
                   cd i2b2-quickstart;
                   ls -l;
                   sh scripts/install/create_wildfly_circleci.sh;
                   #mkdir -p i2b2-quickstart/local/unzipped_packages;
                   #cp -r edu* i2b2-quickstart/local/unzipped_packages/;
                   
                                       
                   
                   #ant clean dist deploy jboss_pre_deployment_setup;
          #echo 'Hello World' 
            #docker build -t $IMAGE_NAME:latest .
workflows:
  version: 2
  build-master:
    jobs:
      - build:
         filters:
            branches:
              only: circle-ci
