version: 2
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
      docker_layer_caching: true    # default - false

  #build:
    #environment:
      #IMAGE_NAME: jonathancardoso/building-on-ci
    #docker:
    #  - image: circleci/openjdk:latest
    #  - image: cibuilds/github:0.10
      
   # machine:
    #  - image: ubuntu-1604:201903-01
      
    steps:
      - checkout 
      #- setup_remote_docker

      - run:
          name: checkout quickstart
          command: cd ..; echo "PWD:$(pwd)";
                   echo "working_directory:${CIRCLE_WORKING_DIRECTORY}";
                   QSDIR="/home/circleci/i2b2-quickstart/";
                   ls -l;
                   git clone --depth 1 https://github.com/waghsk/i2b2-quickstart;
                   cd i2b2-quickstart;
                   ls -l;
      - run:
          name: copy src into local
          command: QSDIR="/home/circleci/i2b2-quickstart/";
                   mkdir -p "${QSDIR}/unzipped_packages/";
                   mv "/home/circleci/project/" "${QSDIR}/unzipped_packages/i2b2-core-server-master/";
                   cd "${QSDIR}/unzipped_packages/";
                   ls -l; 

          
      - run:
          name: "create tar release"
          command: |
                   QSDIR="/home/circleci/i2b2-quickstart/";
                   cd "${QSDIR}/unzipped_packages/i2b2-core-server-master/";
                   SHORT_COMMIT_ID=123;#$(git rev-parse --short=7 ${COMMIT})
                   TAR="${CIRCLE_PROJECT_REPONAME}-${SHORT_COMMIT_ID}.tar.gz" 
                   tar -czf "$TAR" *
                   ls -l
                   mkdir -p "${QSDIR}/workspace/.artifacts/"
                   mv "$TAR" "${QSDIR}/workspace/.artifacts/"
                   ls -l
                   
      - persist_to_workspace: # Persist the specified paths (workspace/echo-output)
      # into the workspace  for use in downstream job. Must be an absolute path,
      # or relative path from working_directory. This is a directory on the container which is
      # taken to be the root directory of the workspace.
          root: ../i2b2-quickstart/workspace
            # Must be relative path from root
          paths:
            - .artifacts
            
      - run:
          name: compile
          command: |
                   QSDIR="/home/circleci/i2b2-quickstart/";
                   cd "${QSDIR}";
                   sh scripts/install/create_wildfly_circleci.sh;
             
          
                   
          #echo 'Hello World' 
            #docker build -t $IMAGE_NAME:latest .
            
  publish-github-release:
    docker:
      - image: cibuilds/github:0.10
    steps:
      - attach_workspace:
          at: ../i2b2-quickstart/workspace
      - run:
          name: "Publish Release on GitHub1"
          command: |
                   VERSION=master-latest
                   ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} i2b2-quickstart/workspace/.artifacts/                           
  
workflows:
  version: 2
  build-master:
    jobs:
      - build:
         filters:
            branches:
              only: circle-ci
              
      - publish-github-release:
          requires:
            - build
          filters:
            tags:
              only: /.*/  #match anything
            #branches:
             # only: circle-ci
            
               

