version: 2
jobs:
  build:
    environment:
      #IMAGE_NAME: jonathancardoso/building-on-ci
    docker:
      - image: circleci/openjdk:latest
    steps:
      - checkout
      #- setup_remote_docker
      - run:
          name: Build Docker image
          command: ls -l;
                   #cd i2b2-core-server-master/edu.harvard.i2b2.server-common;
                   #ant clean;
          #echo 'Hello World' 
            #docker build -t $IMAGE_NAME:latest .
workflows:
  version: 2
  build-master:
    jobs:
      - build:
         filters:
            branches:
              only: circle-ci
