version: 2
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
      docker_layer_caching: true    # default - false

  #build:
    #environment:
      #IMAGE_NAME: jonathancardoso/building-on-ci
    #docker:
    #  - image: circleci/openjdk:latest
    #  - image: cibuilds/github:0.10
      
   # machine:
    #  - image: ubuntu-1604:201903-01
      
    steps:
      - checkout 
      #- setup_remote_docker
      - run:
          name: checkout quickstart
          command: cd ..; echo "PWD:$(pwd)";
                   echo "working_directory:${CIRCLE_WORKING_DIRECTORY}";
                   QSDIR="/home/circleci/i2b2-quickstart/";
                   ls -l;
                   git clone --depth 1 https://github.com/waghsk/i2b2-quickstart;
                   cd i2b2-quickstart;
                   ls -l;
      - run:
          name: copy src into local
          command: QSDIR="/home/circleci/i2b2-quickstart/";
                   mkdir -p "${QSDIR}/unzipped_packages/";
                   mv "/home/circleci/project/" "${QSDIR}/unzipped_packages/i2b2-core-server-master/";
                   cd "${QSDIR}/unzipped_packages/";
                   ls -l; 
      - run:
          name: "install ghr"
          command: |
                   sudo add-apt-repository ppa:longsleep/golang-backports
                   sudo apt-get update
                   sudo apt-get install golang-go
          
      - run:
          name: "create tar release"
          command: |
                   QSDIR="/home/circleci/i2b2-quickstart/";
                   cd "${QSDIR}/unzipped_packages/i2b2-core-server-master/";
                   SHORT_COMMIT_ID=123;#$(git rev-parse --short=7 ${COMMIT})
                   TAR="${CIRCLE_PROJECT_REPONAME}-${SHORT_COMMIT_ID}.tar.gz" 
                   tar -czf "$TAR" *
                   ls -l
                   mkdir -p "${QSDIR}/.artifacts/"
                   mv "$TAR" "${QSDIR}/.artifacts/"
                   ls -l
                   
      - run:
          name: "Publish current commit Release on GitHub"
          command: |
                   VERSION=master-latest
                   ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ./artifacts/                             
         
      - run:
          name: compile
          command: |
                   QSDIR="/home/circleci/i2b2-quickstart/";
                   cd "${QSDIR}";
                   sh scripts/install/create_wildfly_circleci.sh;
                   #cp -rv  "${CIRCLE_WORKING_DIRECTORY}" "${QSDIR}/local/unzipped_packages/";
                   #
                   #ls -l "${QSDIR}/local/unzipped_packages/";
                   #
                   #mkdir -p i2b2-quickstart/local/unzipped_packages;
                   #cp -r edu* i2b2-quickstart/local/unzipped_packages/;
          
                   
          #echo 'Hello World' 
            #docker build -t $IMAGE_NAME:latest .
workflows:
  version: 2
  build-master:
    jobs:
      - build:
         filters:
            branches:
              only: circle-ci
