version: 2
jobs:
  build:
    environment:
      #IMAGE_NAME: jonathancardoso/building-on-ci
    docker:
      - image: circleci/openjdk:latest
    steps:
      - checkout
      #- setup_remote_docker
      - run:
          name: Build Docker image
          command: ls -l;
                   git clone --depth 1 https://github.com/waghsk/i2b2-quickstart
                   cd i2b2-quickstart
                   mkdir -p i2b2-quickstart/local/unzipped_packages;
                   cp -r edu* i2b2-quickstart/local/unzipped_packages/;
                   ls -l;
                   sh scripts/install/create_wildfly_circleci.sh;
                                       
                   
                   #ant clean dist deploy jboss_pre_deployment_setup;
          #echo 'Hello World' 
            #docker build -t $IMAGE_NAME:latest .
workflows:
  version: 2
  build-master:
    jobs:
      - build:
         filters:
            branches:
              only: circle-ci
